import hall from './hall.jpeg'
import hall1 from './hall1.jpeg'
import hal2 from './hall2.jpeg'
import hal3 from './hall3.jpeg'
import hall4 from './hall4.jpeg'
import wedding0 from './wedding0.jpeg'
import wedding1 from './wedding1.jpeg'
import wedding2 from './wedding2.jpeg'
import wedding3 from './wedding3.jpeg'
import wedding4 from './wedding4.jpeg'
import wedding5 from './wedding5.jpeg'
import art1 from './art1.jpeg'
import art2 from './art2.jpg'
import nav0 from './navratri0.jpg'
import nav2 from './navratri2.jpeg'
import nav3 from './navratri3.jpeg'
import photo0 from './photo.jpeg'
import photo1 from './photo1.jpg'
import photo5 from './photo5.jpeg'
import photot6 from './photo6.jpeg'

export {hall, hall1, hal2, hal3, hall4, wedding0, wedding1, wedding2, wedding3, wedding4, wedding5, art1, art2, nav0, nav2, nav3, photo0, photo1, photo5, photot6}